name: Add features and bugs to project
on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/JRichlen/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}