name: Pipeline

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'cypress/**'
      - '.github/workflows/pipeline.yml'
      - '*'  # Files in root directory only

jobs:
  install:
    uses: ./.github/workflows/install-step.yml

  test:
    uses: ./.github/workflows/shared-step.yml
    needs: install
    with:
      command: npm test

  lint:
    uses: ./.github/workflows/shared-step.yml
    needs: install
    with:
      command: npm run lint

  build:
    uses: ./.github/workflows/shared-step.yml
    needs: install
    with:
      command: npm run build

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: [build, test, lint]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4