name: Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  install:
    uses: ./.github/workflows/install-step.yml

  test:
    uses: ./.github/workflows/shared-step.yml
    needs: install
    with:
      command: npm test

  lint:
    uses: ./.github/workflows/shared-step.yml
    needs: install
    with:
      command: npm run lint

  build:
    uses: ./.github/workflows/shared-step.yml
    needs: install
    with:
      command: npm run build

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: [build, test, lint]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4